// Build the CC wiki bundle consumed by the cc-chat edge function.
//
//   deno run -A scripts/build-cc-wiki.ts           # regenerate
//   deno run -A scripts/build-cc-wiki.ts --check   # CI: fail if stale or invalid
//
// Reads docs/cc-wiki/*.md (README.md excluded), validates frontmatter, and
// writes supabase/functions/_shared/cc/wiki.generated.ts.

const SRC = new URL("../docs/cc-wiki/", import.meta.url);
const OUT = new URL("../supabase/functions/_shared/cc/wiki.generated.ts", import.meta.url);
const ROLES = ["staff", "clinic_admin", "admin"] as const;
type Role = typeof ROLES[number];

type Route = { path: string; minRole: Role; label: string };
type Page = { id: string; title: string; summary: string; roles: Role; routes: Route[]; updated: string; body: string };

const errors: string[] = [];

function parse(file: string, text: string): Page | null {
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) { errors.push(`${file}: missing frontmatter`); return null; }
  const fm: Record<string, string> = {};
  const routes: Route[] = [];
  let inRoutes = false;
  for (const line of m[1].split("\n")) {
    if (/^\s+-\s/.test(line) && inRoutes) {
      const [path, minRole, label] = line.replace(/^\s+-\s/, "").split("|").map((s) => s.trim());
      if (!path?.startsWith("/") || !ROLES.includes(minRole as Role) || !label) {
        errors.push(`${file}: bad route line "${line.trim()}" (want "- /path | role | Label")`);
      } else routes.push({ path, minRole: minRole as Role, label });
      continue;
    }
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    inRoutes = kv[1] === "routes" && kv[2].trim() === "";
    fm[kv[1]] = kv[2].trim();
  }
  for (const k of ["id", "title", "summary", "roles", "updated"]) {
    if (!fm[k]) errors.push(`${file}: missing "${k}"`);
  }
  if (fm.id && !/^[a-z0-9-]+$/.test(fm.id)) errors.push(`${file}: id must be lowercase-kebab`);
  if (fm.id && `${fm.id}.md` !== file) errors.push(`${file}: id "${fm.id}" must match file name`);
  if (fm.roles && !ROLES.includes(fm.roles as Role)) errors.push(`${file}: roles must be one of ${ROLES.join(", ")}`);
  if (fm.updated && !/^\d{4}-\d{2}-\d{2}$/.test(fm.updated)) errors.push(`${file}: updated must be YYYY-MM-DD`);
  if (fm.summary && fm.summary.length > 200) errors.push(`${file}: summary over 200 chars`);
  return {
    id: fm.id, title: fm.title, summary: fm.summary, roles: fm.roles as Role,
    routes, updated: fm.updated, body: m[2].trim(),
  };
}

const pages: Page[] = [];
for await (const entry of Deno.readDir(SRC)) {
  if (!entry.isFile || !entry.name.endsWith(".md") || entry.name === "README.md") continue;
  const p = parse(entry.name, await Deno.readTextFile(new URL(entry.name, SRC)));
  if (p) pages.push(p);
}
pages.sort((a, b) => a.id.localeCompare(b.id));

if (!pages.some((p) => p.id === "overview")) errors.push("an overview.md page is required");
if (!pages.some((p) => p.id === "changelog")) errors.push("a changelog.md page is required");

if (errors.length) {
  console.error("CC wiki errors:\n  " + errors.join("\n  "));
  Deno.exit(1);
}

// Content hash → WIKI_VERSION (logged with each CC request).
const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(pages)));
const version = Array.from(new Uint8Array(digest)).slice(0, 6).map((b) => b.toString(16).padStart(2, "0")).join("");

const out =
  `// GENERATED by scripts/build-cc-wiki.ts from docs/cc-wiki/*.md — do not edit.\n` +
  `// Regenerate: deno run -A scripts/build-cc-wiki.ts\n\n` +
  `export type WikiRole = "staff" | "clinic_admin" | "admin";\n` +
  `export type WikiRoute = { path: string; minRole: WikiRole; label: string };\n` +
  `export type WikiPage = { id: string; title: string; summary: string; roles: WikiRole; routes: WikiRoute[]; updated: string; body: string };\n\n` +
  `export const WIKI_VERSION = ${JSON.stringify(version)};\n\n` +
  `export const WIKI_PAGES: WikiPage[] = ${JSON.stringify(pages, null, 2)};\n`;

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(OUT).catch(() => "");
  if (current !== out) {
    console.error("_shared/cc/wiki.generated.ts is stale. Run: deno run -A scripts/build-cc-wiki.ts");
    Deno.exit(1);
  }
  console.log(`CC wiki OK: ${pages.length} pages, version ${version}`);
} else {
  await Deno.writeTextFile(OUT, out);
  console.log(`Wrote ${pages.length} pages, version ${version}`);
}
